### PR TITLE
Fix Credo message types

### PR DESCRIPTION
**Pull request by Sgiath**
Credo uses more message types then currently present. This causes to fallback to error messages. So fo example "Software Design" message "TODO comment" is reported as error.

I would like to report "Software Design" and "Code Readability" as "Info message" I can see that there is config for `info_sign` but I was able to find only examples of warning and error messages. If it is possible to mark some message as "Info message" I would happily change that.

For comparison relevant lines form neomake credo checker https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/elixir.vim#L10

### CODE REVIEW

**Comment by Sgiath** [comment]
@w0rp added tests.
So it is not possible to set message type as "Info"? Why is there `info_sign` then?

**Comment by w0rp** [comment]
@Sgiath Use `'I'` for "info" messages. Search for signs in the documentation for how to set different signs for info. The warning signs are used for info by default.

**Comment by Sgiath** [comment]
Hmm I guess I just didn't search enough :) thanks

**Comment by Sgiath** [comment]
@w0rp fixed

**Comment by Sgiath** [comment]
@w0rp what do you think? Can you approve it or should I make some other changes?

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by Sgiath** [comment]
Hope you are well now :) thanks for your effort!

**Pull request merged**
