### PR TITLE
[doc] Add swift support documentation

### PR DESCRIPTION
**Pull request by namolnad**
Adds Swift support/help documentation in support of #2420 

@w0rp hopefully this is on track for what you had in mind — if not, definitely let me know and I can adjust. Thanks!

### CODE REVIEW

**Comment by w0rp** [comment]
Check the CI server results. You should update the table of contents in the main file to link to the linter options. The bullet point list in the vim help file has to be updated to match the Markdown file.

**Comment by w0rp** [comment]
The other file you need to edit is here: https://github.com/w0rp/ale/blob/master/doc/ale-supported-languages-and-tools.txt

If the items aren't sorted alphabetically and don't match each other, the test scripts will complain.

**Comment by namolnad** [comment]
Awesome, thanks. Couldn't figure out where I was going wrong. Will push a change shortly.

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by namolnad** [comment]
Thanks for the help on this!

**Pull request merged**
