### PR TITLE
Add original filename to SyntaxErl command

### PR DESCRIPTION
**Pull request by dmitrivereshchagin**
This little change adds original filename to SyntaxErl command. It makes linting with SyntaxErl much more clever.

It's all thanks to @urbanserj's changes in SyntaxErl 😇

### CODE REVIEW

**Comment by dmitrivereshchagin** [comment]
Done.

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by w0rp** [comment]
@dmitrivereshchagin Hmm, I had a look, and it doesn't look like there's a stable release which contains this argument. It's hard to tell because there's no changelog. We might have to make this optional and turn it off for now.

**Comment by w0rp** [comment]
See here: https://github.com/w0rp/ale/commit/20e64fbae092e7307c4f01d82fa0e0082c3bb1cb

I made this optional and turned it off by default, so old versions will continue to work. The option can be turned on by default in future, after enough stable versions which support the option have been out for a while.

**Comment by dmitrivereshchagin** [comment]
Oh. You are right. Thank you! 🍻

**Pull request merged**
