### PR TITLE
prettier: Support experimental languages (Handlebars)

### PR DESCRIPTION
**Pull request by dcyriller**
In case the filetype has an exprimental support in Prettier, the --parser flag has to be set manually.

I'm not 100% sure if it's relevant or not to tie ale to an experimental flag in Prettier. But the patch is done, so I leave it to your judgement @w0rp 🙂.

For the time being, I'm using this workaround: https://github.com/w0rp/ale/issues/2247#issuecomment-457660222

Would close https://github.com/w0rp/ale/issues/2247

### CODE REVIEW

**Comment by w0rp** [comment]
Actually, that doesn't work. Because of the compound filetype and `html` being matched first, it selected the wrong parser. In that case, just use the first filetype check to set `l:parser` to `'glimmer'`, and check `!exists('l:parser')`.

**Comment by dcyriller** [comment]
And what do you say of switching `html` and `handlebars` lines in `l:prettier_parsers` definition (with a comment)? I liked your solution being so light.

**Comment by dcyriller** [comment]
> And what do you say of switching html and handlebars lines in l:prettier_parsers definition (with a comment)? I liked your solution being so light.

This doesn't work. Your suggestion is implemented.

**Comment by w0rp** [comment]
That's much better. Cheers! :beers:

**Pull request merged**
