### PR TITLE
fix phpcs linter error: 'option --stdin-path' not known'

### PR DESCRIPTION
**Pull request by dementor5**
Good afternoon! the syntax of phpcss has changed:
ERROR: option "--stdin-path=/home/me/project/update/load.php" not known.

I simple remove key "--stdin-path" and all work again.

### CODE REVIEW

**Comment by capjo** [comment]
Tests in file "test_phpcs_command_callback.vader" are failing. Remove the --stdin-path also there.

**Comment by capjo** [comment]
Which version of phpcs are you using?

I couldn't find any hints that this option was removed.

**Comment by w0rp** [comment]
That option exists. You should update `phpcs` to a newer version.

**Comment by dementor5** [comment]
> That option exists. You should update `phpcs` to a newer version.
Thank you! My version was 2.2.0.
All ok after update on 3.3.2.
Excuse me for troubling.

**Pull request closed without merging**
