### PR TITLE
SugarSS + stylelint support & minor typos

### LINKED ISSUE #877: Add linters for sugarss
```
 Current Filetype: sugarss
Available Linters: []
  Enabled Linters: []
 Linter Variables:

 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'javascript': ['flow', 'eslint', 'standart'], 'sugarss': ['stylelint'], 'css': ['stylelint']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

### PR DESCRIPTION
**Pull request by toastal**
Adds [SugarSS](https://github.com/postcss/sugarss) support via `stylelint`.

Bonus: [SASS -> Sass](http://sassnotsass.com/) and a typo of "asssumed".

fixes #877

- - -

The commit seems to work fine for me on my own `.sss` files. That said, my tests are failing and I don't really understand VimL/Vader or what's going on here. Basically I copied and did a `s/scss/sugarss/g` for previous stylelint stuff. I could use a little help understanding why my own tests are failing while the SCSS and Less files completed successfully with similar setups.

```
  Starting Vader: /testplugin/test/command_callback/test_sugarss_stylelint_command_callback.vader
    (1/3) [EXECUTE] node_modules directories should be discovered
    (1/3) [EXECUTE] (X) ['/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint', '''/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint''  --syntax=sugarss --stdin-filename %s'] should be equal to ['/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint', '''/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint'' --stdin-filename %s']
    (2/3) [EXECUTE] The global override should work
    (2/3) [EXECUTE] (X) ['foobar', '''foobar''  --syntax=sugarss --stdin-filename %s'] should be equal to ['foobar', '''foobar'' --stdin-filename %s']
    (3/3) [EXECUTE] Extra options should be configurable
    (3/3) [EXECUTE] (X) ['stylelint', '''stylelint''  --whatever --syntax=sugarss --stdin-filename %s'] should be equal to ['stylelint', '''stylelint'' --whatever --stdin-filename %s']
  Success/Total: 0/3
```

### CODE REVIEW

**Comment by toastal** [comment]
@w0rp I mean yeah, but I don't understand why they're failing.

**Comment by toastal** [comment]
The new tests failed because the output doesn't match the expected values." is what the console logged, but I still don't understand what that means in this context. This branch has been working for me at my day job so I've just been keeping this branch up to date as I don't have a lot of time learn VimL, read up on the testing framework, and debug all of this.

**Comment by w0rp** [comment]
```
 Starting Vader: /testplugin/test/command_callback/test_sugarss_stylelint_command_callback.vader
    (1/3) [EXECUTE] node_modules directories should be discovered
    (1/3) [EXECUTE] (X) ['/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint', '''/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint''  --syntax=sugarss --stdin-filename %s'] should be equal to ['/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint', '''/testplugin/test/command_callback/stylelint_paths/node_modules/.bin/stylelint''  --stdin-filename %s']
```

The tests fail because the expected output doesn't match the actual output. The linter file has `--syntax=sugarss` in it, and you'll need to add that into the tests and run them again. Try running them with `./run-tests -q`. You'll need to have a working Docker install, and the tests will run better on Linux.

**Comment by w0rp** [comment]
See `:help ale-development-tests` for lots of information on the tests, and how to run them.

**Comment by w0rp** [comment]
Superseded by #2219.

**Pull request closed without merging**
