### PR TITLE
Supporting filtered jump

### PR DESCRIPTION
**Pull request by Lattay**
This pull request address #2198.
I used extra argument to generalized `ale#loclist_jumping#Jump` and `ale#loclist_jumping#FindNearest` to the use of a filter on the type of error. You can now use `:ALENext 1 E` to jump to the next error ignoring warnings with wrapping. I added the corresponding <plug> binding to ease creating of custom shortcut.

PS: This is my first attempt at coding in a Vim plugin and at making a pull request, so I may have forgotten something but I would be glad to fix anything not orthodox.

### CODE REVIEW

**Comment by Lattay** [comment]
Ok, I think that flag combinations are better than lots of specialized flags so I propose the following:
* default behavior is no wrapping, all types and all subtypes
* a flag -wrap enable wrapping
* three flags -error, -warning and -info (mutually exclusives) enable type filtering
* two flags -style and -nostyle (mutually exclusives) enable subtype filtering
The three kind of flags can be used in any order.
A wrapper prepare the arguments of ale#loclist_jumping#Jump from the list of flags and call the function.

**Comment by w0rp** [comment]
Sounds good to me. Keep the existing commands around, and we can add deprecation warnings for them.

**Comment by w0rp** [comment]
Check out 19cc724807de4cdf9f8147c70932b49a79a7f7ee and examples in `test/test_parse_command_args.vader`. I have now added a function for parsing command arguments we can use everywhere.

**Comment by Lattay** [comment]
> Check out [19cc724](https://github.com/w0rp/ale/commit/19cc724807de4cdf9f8147c70932b49a79a7f7ee) and examples in `test/test_parse_command_args.vader`. I have now added a function for parsing command arguments we can use everywhere.

I can use ale#args#Parse but I will have the same content in the wrapper: a loop over the list of flags that modify the arguments to be passed.
So I think using it will only duplicate the logic.

By the way I have now updated \<plug\> bindings and tests as well as documentation and I think it may be ready.
What do you think ?

**Comment by w0rp** [comment]
Use the new function to parse the arguments.

**Comment by Lattay** [comment]
OK, done @w0rp. The behavior in case of multiple exclusive flags is a bit less intuitive but since it should not happen normally it is not a problem.

**Comment by w0rp** [comment]
Cheers! :beers:

**Pull request merged**
