### PR TITLE
Add clang to cpp linters.

### PR DESCRIPTION
**Pull request by tomotanakamura**
I've added clang for CPP language.

### CODE REVIEW

**Comment by w0rp** [comment]
Looks okay to me. We should probably replace the `command` string with a `command_callback`, which will let users change the options for the linter dynamically. It's probably not a big deal for this linter.

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by tomotanakamura** [comment]
Cheers! 🍺 
#134 and #227 were resolved.Would you please close them?

**Comment by w0rp** [comment]
Done.

**Pull request merged**
