### PR TITLE
Added A.L.E. glass logo and source PSD file.

### PR DESCRIPTION
**Pull request by bhalash**
In regard issue #8: It was just a question of free time. 

The source PSD file uses the following typefaces:

* [Bebas Neue][1], available under the SIL Open Font License, Version 1.1.

[1]: http://www.dafont.com/bebas-neue.font "Bebas Neue"

### CODE REVIEW

**Comment by neersighted** [comment]
There is no third period, after the letter E? Is that intentional?

**Comment by bhalash** [comment]
@neersighted Yep, for the sake of symmetry.

**Comment by w0rp** [comment]
@bhalash This is pretty awesome, thanks!

If I'm going to put this into the README so you can see it on GitHub, is there something that should be done with resizing the logo, taking a background away, etc.?

I think I'll add a "Special Thanks" section to the help doc and mention your contribution with the logo in it.

**Comment by bhalash** [comment]
@w0rp Let me know how you'd like it cropped and such. I can also throw up some variations (with/without background).

**Comment by w0rp** [comment]
I'm a fan of the layout used by isort on GItHub. https://github.com/timothycrosley/isort Although here the logo is more a vertical logo than a horizontal logo.

**Comment by bhalash** [comment]
@w0rp Grand, I'll update the PR with more sizes tomorrow.

**Comment by w0rp** [comment]
Cool. Thank you for contributing a cool logo!

**Comment by w0rp** [comment]
Looking pretty good! I'll add this into the README soon enough. Thank you for making this logo.

**Comment by w0rp** [comment]
Thanks again for the cool logo. :+1: I resized the PNG to 50%, exported it at decent quality without making it too big, and put it up in the README file. It looks pretty cool. I added a "Special Thanks" section to the help file mentioning you and linking to your website.

I downloaded a copy of the PSD file and such. I suppose they can be separately hosted somewhere. I might add them to a GitHub pages... thing.

**Comment by w0rp** [comment]
If you look at the logo and think that the settings I used for GIMP are terrible, or background could be something else, just open up a pull request whenever.

**Pull request closed without merging**
