### PR TITLE
Allows ale to leverage npx on-demand / no-install cli task for bash-l…

### PR DESCRIPTION
**Pull request by devendor**
…anguage-server execution.

Where are the tests? Have you added tests? Have you updated the tests? Read the
comment above and the documentation referenced in it first. Write tests!

Seriously, read `:help ale-development` and write tests.

### CODE REVIEW

**Comment by devendor** [comment]
I agree with you and got half way through a failed attempt before bumping into my own lack of experience with vimscript and the codebase.

How about something like this:

```
g:ale_sh_language_server_alias = '%s -s bash-language-server ' 
g:ale_sh_language_server_executable = 'npx'
```

I don't have the time to make it so right now since I'd have to bone up on my vimscript, and I've to pay some bills, but it's a better design.

**Comment by andreypopp** [comment]
Just as a data point I want a similar feature but for [esy](https://esy.sh)
(which is a sandboxed dev workflow) where all tools installed (even native) is
available locally:

```
% esy prettier
% esy ocamlmerlin
```

Thus I want ALE to know how to invoke them and also lookup commands within the
env with:

```
% esy which prettier
```

**Comment by w0rp** [comment]
Okay, you can open another issue for that.

**Comment by w0rp** [comment]
What I'll do for now is close this PR, and we can come up with a better design that covers everything elegantly. In the meantime, you can use `g:ale_command_wrapper` to run linter commands via a script, so you can use `npx` personally, or you can maintain your own fork with this in, or write your own custom linter. You can replace ALE linters with your own overrides, at your own risk.

**Pull request closed without merging**
