### PR TITLE
Use correct exclusion flag in rubocop fixer

### LINKED ISSUE #2032: rubocop fixer throws
## Information

**VIM version**

NVIM v0.3.0
Operating System: macos 10.14

## What went wrong

https://github.com/w0rp/ale/pull/2024 broke rubocop fixer for me, I believe the correct argument is `--force-exclusion` instead of `--force-exclusions`

If you call rubocop directly:
```
$ rubocop --force-exclusions my_file.rb
invalid option: --force-exclusions
```

I'm on latest rubocop v0.60.0

## Reproducing the bug

1. ALEFix on ruby file
2. ALEInfo should show fixer return exit code 2

### :ALEInfo
```
(finished - exit code 2) ['/bin/zsh', '-c', '''bundle'' exec rubocop --config ''/Users/maxhung/work/__/.rubocop.yml'' --auto-correct --force-exclusions ''/var/folders/pr/jdmp_r290dvbh1sd7x9bl52h0000gn/T/nvim2oQs3o
/7/user_type.rb''']
```

### PR DESCRIPTION
**Pull request by maxhungry**
close #2032 

Also tested with issue in #1580, seems to work.

### CODE REVIEW

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by deivid-rodriguez** [comment]
Thank you! :1st_place_medal:

**Comment by jpowell** [comment]
@maxhungry Thanks for fixing this... i don't know what i was thinking when i pushed the other... it didn't actually include exclusions because of tempfiles (path matching issue), and i panicked and misread docs...

In all, thanks!

**Comment by maxhungry** [comment]
@jpowell all good mate, thanks for your work

**Pull request merged**
