### PR TITLE
Add :ALEFirst and :ALELast commands

### LINKED ISSUE #608: Suggestion: add :ALE{First,Last} navigation commands
At present, `:h ale-navigation-commands` lists the following:

* `:ALEPrevious`
* `:ALEPreviousWrap`
* `:ALENext`
* `:ALENextWrap`

For the sake of completeness, it would be nice to also have:

* `:ALEFirst`
* `:ALELast`

Vim's built-in list navigation commands set lots of precedents for this:

* arglist: `:first`, `:last`, `:prev`, `:next` (prev/next DO NOT wrap)
* buflist: `:bfirst`, `:blast`, `:bprev`, `:bnext` (prev/next DO wrap)
* quickfixlist: `:cfirst`, `:clast`, `:cprev`, `:cnext`
* etc. 

I'd like to set up [unimpaired-style mappings](https://github.com/tpope/vim-unimpaired/blob/7bbbca73233b1492a8c3d16f91f34340eccc9b30/doc/unimpaired.txt#L12-L41) for `:ALE{Previous,Next,First,Last}`.

Would you accept a PR adding these commands?

### PR DESCRIPTION
**Pull request by nelstrom**
Closes #608

### CODE REVIEW

**Comment by nelstrom** [comment]
@w0rp do you want Vader tests for this?

**Comment by nelstrom** [comment]
I've added tests for `ale#loclist_jumping#JumpToIndex()`. They pass on my machine, but not on CI.

**Comment by w0rp** [comment]
I replaced the tests with tests that pass in the Docker image.

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by nelstrom** [comment]
Nice one. Thanks for fixing the tests and accepting the PR.

**Pull request merged**
