### PR TITLE
Add prettier to list of JS checkers

### PR DESCRIPTION
**Pull request by jackfranklin**
Thought that Ale didn't support Prettier, but when looking through the code I found `prettier.vim` so it looks like it does, so made this PR. If I've got something wrong then apologies for the noise!

### CODE REVIEW

**Comment by jackfranklin** [comment]
I've just noticed Prettier is a _fixer_, not a _checker_, which makes sense. I wonder if it should be listed somewhere in the README though? It would be easy for someone to think Ale doesn't support it.

**Comment by adriaanzon** [comment]
Yeah, it would make sense to me for the first section of the readme to have a *linters* and *fixers* subsection. The other fixers still need to be listed too though, because the fixing feature is still quite new.

I would also vote for a dedicated `ale_fixers` folder. Currently they live in `autoload/ale/handlers`, together with the generalized handlers. Any thoughts about that @w0rp? Have you considered doing that?

**Comment by w0rp** [comment]
The `ale_fixers` directory doesn't need to exist, as the fixers are loaded differently. The way fixing works, it's basically the opposite of linting.

For the linters, ALE searches `runtimepath` to load everything it can find, and you can filter the list of linters down if you only want to run a few. ALE tries to check your file with anything it can find by default.

For fixing files, ALE doesn't load anything automatically. You pass a series of short names registered in the registry, function names, Funcref values, or lambdas, and ALE runs everything you gave it to fix the files. So, ALE doesn't need to search the `runtimepath`.

What we could do is move more of the functions for fixing things into the `fix` directory, so the first party function names would all be `ale#fix#...`.

**Comment by w0rp** [comment]
I think we should add a second table to the README. List all of the tools for linting things in one table, and all of the tools for fixing things in the other table.

**Comment by w0rp** [comment]
Hmm, actually, just put them all in the same table.

**Comment by adriaanzon** [comment]
Makes sense. I only glanced over how fixers are registered, and that was what came to my mind first.  

> What we could do is move more of the functions for fixing things into the fix directory, so the first party function names would all be ale#fix#....

Yep, that would be fine too 👍

**Comment by w0rp** [comment]
I have added these to the README and the main online documentation file now.

**Pull request closed without merging**
