### PR TITLE
flake8: Move to the buffer's directory before running flake8 command

### PR DESCRIPTION
**Pull request by inducer**
This is analogous to #1487, but for `flake8`, which looks at `setup.cfg` [and a number of other files](http://flake8.pycqa.org/en/latest/user/configuration.html?highlight=setup.cfg) relative to the buffer directory.

### CODE REVIEW

**Comment by w0rp** [comment]
There shouldn't be a need to do this for `flake8`, it ought to figure out where the configuration files are based on the filename parameter.

**Comment by inducer** [comment]
> There shouldn't be a need to do this for flake8, it ought to figure out where the configuration files are based on the filename parameter.

I have found this to be not quite true. If I open a file using `fzf.vim` (my default mode of opening a file at this point), the `flake8` config from the current working directory (if any) appears to be used.

**Comment by inducer** [comment]
Also, thanks for taking a look!

**Comment by reshleman** [comment]
This appears to prevent the usage of `b:ale_python_flake8_options` to specify an explicit `--config` which is relative to the buffer directory.

I think this would affect pylint, too, except `g:ale_python_pylint_change_directory` allows this behavior to be overridden for pylint. I don't see anything comparable for flake8 in the docs.

Thoughts?

**Comment by w0rp** [comment]
Open an issue for adding that option.

**Pull request merged**
