### PR TITLE
doc(readme: faq): add note about manually calling completion instantly

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by w0rp** [comment]
These functions aren't part of the public API. Instead, we should add a command for this, and tests for the command.

**Comment by actionless** [comment]
command for `function! MyAleCompletion()` or for both un-exposed functions which i am calling there?

**Comment by w0rp** [comment]
The `ale#completion` functions there shouldn't be called outside of the codebase. They could be changed at any time. We should add a command for triggering completion manually,  with a Plug keybind, and a setting for disabling automatic completion.

**Comment by actionless** [comment]
>  and a setting for disabling automatic completion.

mb just to make it use `g:ale_completion_enabled`?

**Comment by w0rp** [comment]
Hmm, yeah I guess you could just left the option off and it would work if you use the new command.

**Comment by RyanSquared** [comment]
@actionless do you want to redo this PR or should we add an issue with a feature request?

**Comment by actionless** [comment]
i wanna redo it (since i am still using `ale`) but not soon (vacation) so i'm closing it

**Comment by actionless** [comment]
but of course i would be more happy if something similar will be implemented as a feature :-)

**Comment by w0rp** [comment]
There's an issue open for it.

**Comment by actionless** [comment]
this one? https://github.com/w0rp/ale/issues/1830

**Pull request closed without merging**
