### PR TITLE
Add rpm spec file linter (rpmlint)

### PR DESCRIPTION
**Pull request by jasontibbitts**
This is a rough attempt at adding a linter for RPM spec files using rpmlint.  It appears to work well enough, but note the following:

* I basically don't know what I'm doing.  I have many years of programming experience but outside of setting variables in my .vimrc, vim isn't something I've done before.
* Some rpmlint errors do not have line numbers.  I just made them show up at line 1 but perhaps there's a better way to handle that.
* The vim modeline reads 'spec' but everyone's going to call them "RPM spec files".  I'm not sure where that should actually go in the documentation.
* Editing vim help files is... weird.  I tried to get things to line up the right way but I'm not sure if it's done the right way.
* I added an entry for the test suite but I didn't try actually running it.  I guess the CI setup will yell at me if it doesn't run properly.

So, anyway, it's a first try.  Please let me know what I can do to make it better.

### CODE REVIEW

**Comment by jasontibbitts** [comment]
Well crap, I check back and now the checks failed.  The log doesn't make it obvious but I would guess I screwed up the test I added.  I guess I'll try to figure out how to run it myself.

**Comment by jasontibbitts** [comment]
I played around with it a bit but no luck.  I am not seeing where the syntax error in my test is, and while I can get the test suite to start, it just hangs after the first incidence of:

```
docker run -a stderr --rm -v /home/tibbs/work/ale:/testplugin -v /home/tibbs/work/ale/test:/home w0rp/ale vim-v8.0.0000 +Vader! test/*.vader test/*/*.va   der test/*/*/*.vader test/*/*/*/*.vader
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

If you have any hints, that would be great.

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by jasontibbitts** [comment]
Thanks!

**Pull request merged**
