### PR TITLE
[lsp] Add Swift / SourceKit-LSP support

### PR DESCRIPTION
**Pull request by namolnad**
# Swift LSP Support
This adds LSP support for Swift via the recently announced/open-source [SourceKit-LSP](https://github.com/apple/sourcekit-lsp). 

Addresses #2147 *(Thanks @TaDaa for the initial work on the fork — this is based on your original work.)*

**Tasks:**
- [x] Add LSP support for Swift via SourceKit-LSP
- [x] Add tests

### CODE REVIEW

**Comment by namolnad** [comment]
Thanks for the feedback @w0rp! I updated with some additional tests based off some existing examples. 

_(Coincidentally after trying to run `:help ale-tests` I also realized I needed to generate help tags for my plugins and used your example in the main README to do that — so thanks for that as well!)_

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by w0rp** [comment]
One thing I forgot, which you can add now, is add the new linter to the list of supported tools in Markdown and in the Vim help file.

**Pull request merged**
