### PR TITLE
[elixir] Rewrite the credo linter to use json output.

### PR DESCRIPTION
**Pull request by archSeer**
Doing so allows us to provide inline information. I asked the maintainer to add a `json` format for the errors, and he did so today! Now we can provide the start and end column information so that ALE can underline the relevant parts.

https://github.com/rrrene/credo/issues/471

Need to wait until a new version of credo is released.

### CODE REVIEW

**Comment by w0rp** [comment]
We could support this by detecting the credo version. Have a look at some of the other linters or fixers which check the version, like `flake8`.

**Comment by w0rp** [comment]
Closed due to inactivity.

**Comment by archSeer** [comment]
Sorry, I was still waiting for an official Credo 0.9 release (currently
rc8), I'll update the code shortly!

**Comment by w0rp** [comment]
Sure, sounds good to me. I'll reopen this. Make sure to add a version check, as with linters like `flake8`, so changing this won't break running earlier versions of the linter.

**Comment by w0rp** [comment]
Closing due to inactivity.

**Pull request closed without merging**
