### PR TITLE
Add textlint for Asciidoc and add it to Fixers

### PR DESCRIPTION
**Pull request by ta2gch**
I made this patch to run textlint at asciidoc too, and also to work `textlint --fix` in `ALEFix`.
Thank you!

### CODE REVIEW

**Comment by ta2gch** [comment]
I got it. However, I think you don't need tests for the linter because the tests are in this repository as for markdown. For example, A linter `write-good` have just one test sets for only markdown but `write-good` covers `asciidoc` too. 

Should I add just the tests for fixer function?

**Comment by ta2gch** [comment]
I added them.

**Comment by w0rp** [comment]
Add tests for the linter. You need to use the `AssertLinter` command. See similar comments in #2190.

**Comment by ta2gch** [comment]
I'm appriciate you to tell me again, I got what you say. I added it, Please check it,

**Comment by w0rp** [comment]
Cheers! :beers:

**Pull request merged**
