### PR TITLE
show rendered cargo error in detail for clippy errors

### PR DESCRIPTION
**Pull request by nerdrew**
Sample clippy output:

```json
{
    "reason": "compiler-message",
    "package_id": "snow_white 0.1.0 (path+file:///Users/lazarus/dev/grim/snow_white)",
    "target": {
        "kind": [
            "lib"
        ],
        "crate_types": [
            "lib"
        ],
        "name": "snow_white",
        "src_path": "/Users/lazarus/dev/grim/snow_white/src/lib.rs",
        "edition": "2018",
        "doctest": true
    },
    "message": {
        "rendered": "warning: You are using an explicit closure for copying elements\n   --> snow_white/src/save.rs:289:21\n    |\n289 |                     pending_seqs.seqs.iter().map(|seq| *seq).collect::<Vec<Seq>>()\n    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: Consider calling the dedicated `copied` method: `pending_seqs.seqs.iter().copied()`\n    |\n    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_clone\n\n",
        "children": [
            {
                "children": [

                ],
                "code": null,
                "level": "help",
                "message": "for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_clone",
                "rendered": null,
                "spans": [

                ]
            },
            {
                "children": [

                ],
                "code": null,
                "level": "help",
                "message": "Consider calling the dedicated `copied` method",
                "rendered": null,
                "spans": [
                    {
                        "byte_end": 11764,
                        "byte_start": 11724,
                        "column_end": 61,
                        "column_start": 21,
                        "expansion": null,
                        "file_name": "snow_white/src/save.rs",
                        "is_primary": true,
                        "label": null,
                        "line_end": 289,
                        "line_start": 289,
                        "suggested_replacement": "pending_seqs.seqs.iter().copied()",
                        "suggestion_applicability": "MachineApplicable",
                        "text": [
                            {
                                "highlight_end": 61,
                                "highlight_start": 21,
                                "text": "                    pending_seqs.seqs.iter().map(|seq| *seq).collect::<Vec<Seq>>()"
                            }
                        ]
                    }
                ]
            }
        ],
        "code": {
            "code": "clippy::map_clone",
            "explanation": null
        },
        "level": "warning",
        "message": "You are using an explicit closure for copying elements",
        "spans": [
            {
                "byte_end": 11764,
                "byte_start": 11724,
                "column_end": 61,
                "column_start": 21,
                "expansion": null,
                "file_name": "snow_white/src/save.rs",
                "is_primary": true,
                "label": null,
                "line_end": 289,
                "line_start": 289,
                "suggested_replacement": null,
                "suggestion_applicability": null,
                "text": [
                    {
                        "highlight_end": 61,
                        "highlight_start": 21,
                        "text": "                    pending_seqs.seqs.iter().map(|seq| *seq).collect::<Vec<Seq>>()"
                    }
                ]
            }
        ]
    }
}

```

The current detail is:
```
You are using an explicit closure for copying elements
```

The new detail is:
```
warning: You are using an explicit closure for copying elements
   --> snow_white/src/save.rs:278:27
    |
278 |         let all_log_ids = logs.keys().map(|log_id| *log_id).collect::<Vec<LogId>>();
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: Consider calling the dedicated `copied` method: `logs.keys().copied()`
    |
    = note: #[warn(clippy::map_clone)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_clone
```

### CODE REVIEW

**Comment by RyanSquared** [comment]
The reason we don't do this as-is (and have had issues with Rust with this in the past) is that ALE does not support multiple lines given there's only one line that can be displayed when hovering over a message. If there's a way to separate `:ALEDetail` from the message ALE shows otherwise, I'd be fine with this.

**Comment by nerdrew** [comment]
I'm not entirely sure what you are asking... is "hovering" the same as having the cursor over it in non-gui vim?

Screen shots:
"hovering" (assuming hovering is having the cursor over the error):
Screen Shot 2019-06-04 at 22 32 15

Detail view:
Screen Shot 2019-06-04 at 22 32 20

**Comment by RyanSquared** [comment]
Right, I totally glossed over the fact that it's only set for the detail and not for the short view. LGTM then. And yeah hovering basically implying that the cursor is above text in the same way hovering would work in a graphical client.

**Comment by nerdrew** [comment]
Thoughts on merging this?

**Comment by w0rp** [comment]
Cheers! :beers:

**Pull request merged**
