### PR TITLE
kotlin linter support for maven/pom.xml

### PR DESCRIPTION
**Pull request by gavocanov**
Added support for getting the classpath from a pom.xml using maven if present, same as the javac implementation.

### CODE REVIEW

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by gavocanov** [comment]
Emacs uses https://github.com/shyiko/ktlint, seems much faster and nicer overall, would be worth taking in consideration.

**Comment by w0rp** [comment]
I'll create an issue for tracking that.

**Comment by w0rp** [comment]
#593 There's the issue.

**Pull request merged**
