### PR TITLE
Luacheck: Respect warn_about_trailing_whitespace option

### PR DESCRIPTION
**Pull request by adriaanzon**
See http://luacheck.readthedocs.io/en/stable/warnings.html, warnings 611 to 614.

### CODE REVIEW

**Comment by adriaanzon** [comment]
Sure thing, I updated the test to check if it leaves out the warning.

**Comment by adriaanzon** [comment]
Sure thing, I updated the test to check if it leaves out the warning.

**Comment by adriaanzon** [comment]
Good idea 🙂 

I finally found some time to sort this out.

**Comment by w0rp** [comment]
Cheers! :beers:

**Pull request merged**
