### PR TITLE
Add support for nvim's virtualtext on cursor

### PR DESCRIPTION
**Pull request by luan**
Addresses #2055. I haven't added tests for this yet and I may have inadvertently violated parts of the development guide. But I was just very excited to play around with this. The API being used here (`nvim_buf_set_virtual_text`) is not yet released on neovim so I'm not sure we'd want to merge this before that happens. I'll look into adding tests for this tomorrow! But I'd love some early feedback on it.

Summary of the changes:
- Add g:ale_virtualtext_cursor boolean to enable/disable it
- Add g:ale_virtualtext_prefix to configure what prefix to use (default:
'> ')
- Requires neovim 0.3.2's unreleased API `nvim_buf_set_virtual_text`

Demo:
[asciicast](https://asciinema.org/a/DUvYWKMpsEM6eLPeQHPKiGkjb)

### CODE REVIEW

**Comment by w0rp** [comment]
It might be a good idea to put support for `virtualtext` messages entirely in their own file, and use separate `autocmd` events for it, which can be set only if the option is enabled. That way, you'll be able to turn echoing messages off, and turn `virtualtext` messages on.

**Comment by luan** [comment]
@w0rp I moved everything to `autoload/ale/virtualtext.vim` as suggested. Decided to extract a shared function into `ale#util` for `ale#util#FindItemAtCursor`. I also split out `g:ale_virutaltext_delay` to have both echo and virtualtext be fully independent of each other.

Wasn't super sure about [this block](https://github.com/w0rp/ale/blob/ba9b056a57a605e1253b9f50e94074499bf808b4/autoload/ale/events.vim#L134-L148) seems like a lot of duplicaiton for the autocmds there. I also didn't quite understand why we needed to check `if exists('*ale#engine#Cleanup')` for those, but I just followed it for the virtualtext bit.

I fixed the tests that the original commit had broken with regards to `ALEInfo`. And I tried to write tests for the specific virutaltext functionality. I ran into two problems with that:
- There is no way (that I could find) to inspect what is the current virutaltext being shown on any given line.
- Even if there was, the tests would depend on an unreleased version of neovim, which the current infrastructure doesn't run against.

**Comment by luan** [comment]
@w0rp, thoughts?

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by ahmedelgabri** [comment]
Not sure what is wrong here but the messages don't get updated when I move the cursor, you can see the normal echo messages in the command line but the virtualtext is not being updated the same way

error

**Comment by babariviere** [comment]
@ahmedelgabri you have to enable option `ale_virtualtext_cursor`

**Comment by ahmedelgabri** [comment]
@babariviere I already enabled it. Otherwise inline error messages wouldn’t have appeared at all.

**Comment by babariviere** [comment]
oh yeah sorry, i haven't see the inline message

**Comment by luan** [comment]
> Nice! I've noticed that for some linters (especially Rust), the error messages are across multiple lines. Does virtualtext only support being displayed on a single line? (As it is now, the error message just has the `\n` characters displayed as `^@` control sequences.)

@alok Yeah, it's on a single line. I actually thought about showing multiline ones, but I got stuck with thinking about when the next line is longer than the previous it would make it hard to present.

@ahmedelgabri I haven't seen anything like that, can you help me reproduce that issue?

**Comment by ahmedelgabri** [comment]
@luan sure, I'm trying to disable plugins & settings one by one to see if I can find the issue. This is my [ale config](https://github.com/ahmedelgabri/dotfiles/blob/master/files/.vim/after/plugin/ale.vim) in case you see something odd or something.

**Comment by megalithic** [comment]
> > Nice! I've noticed that for some linters (especially Rust), the error messages are across multiple lines. Does virtualtext only support being displayed on a single line? (As it is now, the error message just has the `\n` characters displayed as `^@` control sequences.)
> 
> @alok Yeah, it's on a single line. I actually thought about showing multiline ones, but I got stuck with thinking about when the next line is longer than the previous it would make it hard to present.
> 
> @ahmedelgabri I haven't seen anything like that, can you help me reproduce that issue?

@luan is it possible to a.) set textwidth for the virtualtext buffer; or b.) have `\n` properly render as newlines? /cc @alok

**Comment by pwntester** [comment]
That is a cool addition, thanks @luan!

Would it be possible to add an option to justify the text to the rigth based on `winwidth(0)` and text length?

**Comment by kristijanhusak** [comment]
Can we use separate highlighting group for this? I would like to use color that doesn't create so much contrast, but if i change any of the ALE* groups, it also changes the coloring on the exact spot where the error is.

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by uri** [comment]
@ahmedelgabri did you ever find the problem? I'm having the same issue.

**Comment by ahmedelgabri** [comment]
@uri Didn't have enough time to debug it yet, I disabled it for the time being.

**Comment by uri** [comment]
@ahmedelgabri if you are looking for virtual text https://github.com/neomake/neomake does it pretty well.

**Comment by maxim-usikov** [comment]
@luan this option just for nvim?

`g:ale_virtualtext_cursor`

**Comment by meain** [comment]
@maxim-usikov yeah, vim does not have support for the feature `virtualtext`.

**Comment by maxim-usikov** [comment]
@meain thanks. 

May be add some notes about that to docs?

**Comment by w0rp** [comment]
I added a sentence to the documentation to clarify that now.

**Pull request merged**
