### PR TITLE
[new linter] The missing old famous splint for C language

### PR DESCRIPTION
**Pull request by skywind3000**
Splint has been widely used for years to analyse C language sources, 
Syntastic supports splint but ale doesn't, so , I added splint for ale.
Most code is borrowed from cppcheck and go.

### CODE REVIEW

**Comment by skywind3000** [comment]
Why did travis ci build fail ? 

```text
  Starting Vader: /testplugin/test/test_load_all_linters.vader
    (1/1) [EXECUTE] Exceptions shouldn't be thrown when loading all linters
    (1/1) [EXECUTE] (X) Vim:E492: Not an editor command: 
      > /testplugin/ale_linters/c/splint.vim, line 3
```

But line 3 in splint.vim is an empty line. How can it be an error ?
something wrong with vader ?

**Comment by w0rp** [comment]
Hello! I finally have some time to look at this now.

**Comment by skywind3000** [comment]
finally, succeeded !
please have a look

**Comment by w0rp** [comment]
Closing due to inactivity.

**Pull request closed without merging**
