### PR TITLE
add php-cs-fixer to list of fixers

### PR DESCRIPTION
**Pull request by jdeniau**
This PR add [php-cs-fixer](http://cs.sensiolabs.org/) to php fixer list

### CODE REVIEW

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by Mte90** [comment]
I wanted to try it but there is no doc about how execute php-cs-fixer or set the standard.
Maybe I am missing something?

**Comment by w0rp** [comment]
See `:help ale-fix`, which explains everything.

**Comment by jdeniau** [comment]
It launches `php-cs-fixer fix` without argument.

You can refer to php-cs-fixer documentation directly.

Personnaly I use https://github.com/mapado/php-cs-fixer-config , it may
help you too

**Pull request merged**
