### PR TITLE
Add support for go_gobuild_options

### PR DESCRIPTION
**Pull request by hasufell**
Use case: `let g:ale_go_gobuild_options = "-gcflags='-e'"`

### CODE REVIEW

**Comment by Carpetsmoker** [comment]
Would it make sense to set the default to `"-gcflags='-e'"` (`-e` limits the number of reported errors; to 10 I believe).
Limiting errors makes sense when building something with `go install` or `go test`, but in the context of ALE it probably makes a bit less sense?

**Comment by hasufell** [comment]
@Carpetsmoker I agree, it's unlikely that you only want the first 10 errors and counter-intuitive.

wrt tests, I have no idea how they work and I am not sure I have the time to look into that right now

**Comment by Carpetsmoker** [comment]
I don't mind picking up from this PR and finishing up with tests etc. if you don't have time. May be a few days though.

**Comment by hasufell** [comment]
I lost interest and use gometalinter now.

**Comment by w0rp** [comment]
I just picked this up and added support for the option now with some tests. I also fixed the setting of `GOPATH` so it should work on Windows, and escaped the paths for `GOPATH` and `cd`.

**Pull request closed without merging**
