### PR TITLE
Add python mypy support

### PR DESCRIPTION
**Pull request by keith**
This adds support for [mypy](mypy-lang.org) the official optional python typechecker.

### CODE REVIEW

**Comment by w0rp** [comment]
Is there anything that must be done for this to get it to recognise imports correctly, say in combination with virtualenv?

**Comment by keith** [comment]
Right now this definitely assumes that you're running vim in an environment where that's already handled. It feels to me like setting that up might be outside of the scope of what this plugin should handle. Thoughts?


--
Keith Smiley

**Comment by renstrom** [comment]
>It feels to me like setting that up might be outside of the scope of what this plugin should handle. Thoughts?

I agree. Setting up a virtualenv (and activating it) is definitely something ALE shouldn't bother itself with. There are other plugins for that:

- https://github.com/lambdalisue/vim-pyenv
- https://github.com/jmcantrell/vim-virtualenv

**Comment by w0rp** [comment]
I'll take this without the virtualenv detection. If enough people complain, it can be addressed later.

Could you change the variable name for the options from `_args` to `_options`? I've started insisting that every linter uses the same name convention for the options here: https://github.com/w0rp/ale/issues/257

**Comment by w0rp** [comment]
I'll just merge this and do that myself. It should only take a few minutes.

**Comment by keith** [comment]
Ah sorry, thanks for doing that! Thanks!


--
Keith Smiley

**Pull request merged**
