### PR TITLE
Marks persist when switching from lintable to not lintable buffer

### PR DESCRIPTION
**Pull request by vavaka**
Hi

Please find below steps to reproduce persistent marks problem:
1. Open lintable file which contains marks
2. From this file switch to not lintable file
You should notice that some letters in not lintable files are highlighted. This happens because Ale does not cleared marks info on buffer switch.

### CODE REVIEW

**Comment by vavaka** [comment]
> The ale_enabled check is needed, so that shouldn't be removed.
`ale_enabled` has not been removed. I just added one more condition for clearing matches state in order it happened when current buffer filetype has no associated linter.

**Comment by w0rp** [comment]
Ah sorry, my bad.

I think this is not quite complete, as the same problem might come up when you open another file which _is_ lintable. I'll think about this.

**Comment by w0rp** [comment]
Yes, the problem occurs with files you can lint as well, as I suspected. A little bit of refactoring and an extra call in the existing cleanup function will fix it. I'll push a commit soon.

**Comment by w0rp** [comment]
Here is the commit: https://github.com/w0rp/ale/commit/d8dcc56af58d1545cf3a7a9f6160d8ba6ad39923

That should cover this case, and changing to any other file in general.

**Pull request closed without merging**
