### PR TITLE
Continue scalac compilation until just before bytecode generation

### PR DESCRIPTION
**Pull request by zackhsi**
Previous behavior does not compile deep enough to surface errors.

See compiler phases:
https://docs.scala-lang.org/overviews/compiler-options/index.html#compilation-phases

### CODE REVIEW

**Comment by w0rp** [comment]
Just to be sure, is there any risk of executing arbitrary code with this change, or is this just a step for generating bytecode which isn't executed? Update the tests to match the changes to the command.

**Comment by zackhsi** [comment]
Nope, no executables/classfiles are produced until the last step, `jvm`, so there is nothing to execute. The specific flag `-Ystop-before:jvm` tells the compiler to stop _before_ the `jvm` step.

**Comment by w0rp** [comment]
Looks good to me. Cheers! :beers:

**Comment by w0rp** [comment]
I had to revert this, as it broke using `scalac` at all for some people. We can consider adding an option for this instead.

**Comment by RyanSquared** [comment]
I did some snooping and came across this page:

https://docs.scala-lang.org/overviews/compiler-options/index.html#compilation-phases

I don't see either `jvm` or `parser`, but I do see `parse`. Is the documentation for this out of date or something? Do we need some kind of version check system?

**Pull request merged**
