### PR TITLE
Close the quickfix/location list window when quitting the parent buffer

### PR DESCRIPTION
**Pull request by smkent**

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
This is awesome! Anyone can tell me how to use this?

**Comment by w0rp** [comment]
I recommend creating the function which is added in the diff here and writing your own `QuitPre` autocmd function. I decided this is such a general thing that it's not worth including.

**Comment by cwonrails** [comment]
Thanks for the advice on how to add this back. I know the original PR didn't add the tests you mentioned @w0rp, but this is a really, really useful option and one I had to hack around to get to work with Syntastic before swapping to ale. Is there some way this can get included in the project?

**Comment by w0rp** [comment]
If and only if you write tests for it.

**Pull request closed without merging**
