### PR TITLE
Disable fixing when linting is disabled

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey, I think it would be a valuable addition to disable fixing when linting is disabled. WDYT?

I will fix the tests if the general change is accepted by you.

### CODE REVIEW

**Comment by w0rp** [comment]
No, you should still be able to fix your files when linting is disabled. If you want to turn both off, turn both off.

**Comment by saschagrunert** [comment]
Okay, may I ask you how to temporarily disable linting in ale? :) There seems no command for that, right?

**Comment by w0rp** [comment]
There is a command for that. `:help ALEDisable`.

**Comment by FuDesign2008** [comment]
But there is no command to disable fixing when `let g:ale_fix_on_save=1` is set in `.vimrc`.  
`let g:ale_fix_on_save = 0`  can disable fixing when saving file on next time. Can ale provide a command like `ALEFixDisable` ?

```
command! -nargs=0 ALEFixDisable :let g:ale_fix_on_save=0

```

**Comment by saschagrunert** [comment]
> But there is no command to disable fixing when `let g:ale_fix_on_save=1` is set in `.vimrc`.
> `let g:ale_fix_on_save = 0` can disable fixing when saving file on next time. Can ale provide a command like `ALEFixDisable` ?
> 
> ```
> command! -nargs=0 ALEFixDisable :let g:ale_fix_on_save=0
> ```

That's what I initially meant :+1: :innocent:

**Comment by w0rp** [comment]
I don't think there's a need for a command like that. The `let` line is enough. The only reason `:ALEDisable` exists is so you can both disable linting, remove autocmd commands, and clear any linter problems that have been set so far.

**Comment by FuDesign2008** [comment]
In order to not keep `g:ale_fix_on_save` in my mind,  I build [FuDesign2008/ale-shim.vim](https://github.com/FuDesign2008/ale-shim.vim) .

**Pull request closed without merging**
