### PR TITLE
[new linter] add stylelint support

### PR DESCRIPTION
**Pull request by diartyz**
add stylelint support for
- css
- scss
- sass

### CODE REVIEW

**Comment by w0rp** [comment]
Looks good to me. :+1:

**Comment by aaronmcadam** [comment]
I'm having trouble getting `stylelint` to pick up my style violations. 

I've tried editing a file within a directory that has a `.stylelintrc` and a nested directory too, but I never see any violations in the gutter.

Is there something special I need to do @diartyz?

**Comment by diartyz** [comment]
@aaronmcadam 
you doesn't need to specify a syntax, it will be automatically inferred by the file extension.
can you get the error when you using stylelint in shell ?
eg: `stylelint path/to/file`

**Comment by aaronmcadam** [comment]
Thanks @diartyz, it turned out that my global `stylelint` was out of date and I was configuring a property that didn't exist with that version. It's working now :smile:

**Comment by diartyz** [comment]
@aaronmcadam 
btw, you can use the local npm package now.
https://github.com/w0rp/ale/pull/226

**Pull request merged**
