### PR TITLE
Add support for markdownlint

### PR DESCRIPTION
**Pull request by tylucaskelley**
This PR adds basic support (and tests) for [markdownlint](https://github.com/DavidAnson/markdownlint). Closes https://github.com/w0rp/ale/issues/1344.

Things for the future that I will add:

1. As of now it only uses the global executable, and I will work on adding support for executables in the `node_modules` directory as well when I have the chance.
2. Right now just uses the default configuration, will add support for custom config filenames / locations.

### CODE REVIEW

**Comment by tylucaskelley** [comment]
Any contributor available to review this?

**Comment by w0rp** [comment]
I'm the only guy available for reviewing anything.

**Comment by w0rp** [comment]
The codes could be put in their own key, but this is fine.

**Comment by w0rp** [comment]
Cheers! :beers:

**Comment by tylucaskelley** [comment]
Gotcha @w0rp, didn't mean to try and rush you! Thanks for getting around to it. Been using Ale for a month or so now and haven't looked back to syntastic since!

**Comment by w0rp** [comment]
Nah, there's no rush. I just happened to finally get some time to look at this now.

**Pull request merged**
