### PR TITLE
Dockerfile linting via hadolint

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by w0rp** [comment]
Yeah, let's give this a go, see what people think about it.

Cheers! :beers:

**Comment by LubergAlexander** [comment]
@hauleth not sure if its a bug or not, but on my system dockerfile filetype is: "Dockerfile"

At the moment the linter is configured for lowercase filetype name, thus it doesn't work out of the box.

I had to define an alias for that:

```
  let g:ale_linter_aliases = {
  \ 'Dockerfile': 'dockerfile',
  \ }
```

Thanks for this linter integration!

**Comment by hauleth** [comment]
On my system everything worked. Maybe @w0rp should add some method to unifying `'filetype'` before searching for available linters.

**Comment by w0rp** [comment]
I'll create a default alias with the uppercase character. That should handle that.

**Comment by w0rp** [comment]
https://github.com/w0rp/ale/commit/97131262abf31de883bcb65835ed6842f66bbd3b There's the commit.

**Comment by LubergAlexander** [comment]
@w0rp thanks!

**Pull request merged**
